### ISSUE TITLE
A Chinese version for README

### ISSUE THREAD

**Issue by C-ld** [megaease/easemesh#155]
Hi @xxx7xxxx, I noticed that you've already provided a very detailed and thoughtful README. May I contribute a Chinese version?

**Comment by zhao-kun** [comment]
Sure, all contributions we will welcom

**Comment by C-ld** [comment]
Thanks for your kind reply @zhao-kun , but I didn't notice that the Chinese version has already been provided in the content... Maybe I can contribute some translation for docs/*.md .

**Comment by xxx7xxxx** [comment]
Thanks for your contribution, your PR has been merged.
