### ISSUE TITLE
Service Migration Automation

### ISSUE THREAD

**Issue by haoel** [megaease/easemesh#16]
This requirement only needs to consider the following scenario:

Customer runs their services in their Kubernetes cluster, we need to migrate their services to ease mesh automatically and safely.

The proposal as below:

1) Install EaseMesh into Kubernetes.
2) List the Kubernetes service deployment, and ask to choose the deployment to need to migrate.
3) Automatically get the current service's deployment YAML and migrate to EaseMesh, and deploy the Mesh version.
4) enable mesh version service and disable the original services gracefully. (can be done by traffic scheduling)

**Comment by xxx7xxxx** [comment]
https://github.com/megaease/easemesh/pull/51 fixed by supporting native deployment of k8s
