### ISSUE TITLE
docker pull megaease/easeagent-initializer get stuck

### ISSUE THREAD

**Issue by StormSpirit22** [megaease/easemesh#50]
I tried many times " docker pull megaease/easeagent-initializer " command,  all get stuck. 
megaease/easemesh-operator and  megaease/easegress can pull normally.
Dose anybody has same problem and how to solve it ?

**Comment by xxx7xxxx** [comment]
It's normal for me to pull it in my machine. Would you please do it again, or use some local network proxy for docker hub

**Comment by zhao-kun** [comment]
It's weird, it's no problem with my own enironments.
So, if you really can't pull it from the docker hub, you could build the image from scratch. The Dockerfile is located at https://github.com/megaease/easeagent/blob/master/rootfs/Dockerfile, but you might need to slightly change its contents in [line 3](https://github.com/megaease/easeagent/blob/master/rootfs/Dockerfile#L3) and [line 5](https://github.com/megaease/easeagent/blob/master/rootfs/Dockerfile#L3), just removed two arguments default value is ok

**Comment by StormSpirit22** [comment]
Thanks for your suggestions. I tried use network proxy and it solved. And I tried building Dockerfile myself, also succeed. Thanks for you two bros.
