### ISSUE TITLE
Supporting mockup service discovery

### ISSUE THREAD

**Issue by haoel** [megaease/easemesh#54]
This requirement comes from the performance test.

Sometimes, in a performance test environment, there are some services that cannot be tested, such as the external service, or SMS or email service. For those services, we need to mock them up.

With the Easegress [mock feature ](https://github.com/megaease/easegress/blob/main/doc/filters.md#mock), we can easy to set up the mock service with some mocked APIs, so we can make sure the test can be smoothly run.

**Comment by benja-wu** [comment]
Already merged.
